### ISSUE TITLE
Compatibility with v7?

### ISSUE THREAD

**Issue by TRIROG** [knalli/homebridge-pilight#1]
Is this compatible with pilight v7?

**Comment by knalli** [comment]
I think I've already verified this (v7 was released 2-3 months ago?), but I'm not sure at the moment. Basically, it only uses the HTTP/WS API. Unless this API has changed, it will work for both versions.

**Comment by TRIROG** [comment]
I couldn't find anything regarding this and only wanted to be sure.
Thanks!

**Comment by knalli** [comment]
I'll verify this later and make a note here.

**Comment by knalli** [comment]
Simply forget this one here. For the records: I'm running v7 and it still works.
