### ISSUE TITLE
Negative temperature values not showing up

### ISSUE THREAD

**Issue by ghost** [knalli/homebridge-pilight#19]
Hi,

I have been trying out some 1-Wire sensors via Pilight this afternoon. Everything works great including the hand-off to homebridge via your awesome plugin. 

There is just one thing I can't figure out: pilight-daemon and hombridge consol both return negative temperature values for my outside sensor (it's about - 2 °C at the moment). Apple Home App and the EVE App only giving me a "0" or "NA". 

I have read about this issue in regards to the homebridge-symcon plugin. Maybe this can help: https://github.com/nfarina/homebridge/issues/480

Especially the fifth post sounds interesting, but I don't now which charcateristic might cause this issue related to the hombridge-pilight plugin. It seems as the standard temperature minimum value is set to 0. The challenge would be to override this setting with something more realistic (like - 50 e.g.).

Looking forward to your input / help!

Thanks and keep up the great work!

Nils

**Comment by ghost** [comment]
Alright, after digging a little deeper I found this thread: https://github.com/DanTheMan827/homebridge-ds18b20/issues/1

So it's actually not a homebridge-pilight issue it seems. Addapting the confing file (as sudo) as described in 1) here (https://github.com/DanTheMan827/homebridge-ds18b20/issues/1#issuecomment-172803222) worked great. I put the min value to -100.

Hope this helps someone else!

**Comment by knalli** [comment]
Thank you. I'll put this into "faq". Maybe someone else find this helpful, too.
