### ISSUE TITLE
Dimmer issue when Homebridge is running

### ISSUE THREAD

**Issue by genfersee** [knalli/homebridge-pilight#35]
Dear all,

I am facing an issue for a long time for which I could not find help on this forum.

When pilight is running without Homebridge and its pluggin Homebridge-pilight, everything works great. For example, dimmers can be dimmed to a proper dim level via GUI or via command line pilight-send.

But when I start Homebridge service, dimmers do not react properly on dim commands via pilight GUI or via command line pilight-send. Switches are operating correctly though.

When checking the pilight logs, I do not see any differences in the commands. How could Homebridge screw this up?
Did anyone face this issue already?

Many thanks for your help,
Genfersee

**Comment by knalli** [comment]
Phew.. I think I need more information. Maybe there will be sent too many (single) dim events, maybe this is responsible for the issue?

* please provide more info, i.e. logging with timestamps
* note the issue corresponding to the relevant log lines

Anyway:
> But when I start Homebridge service, dimmers do not react properly on dim commands via pilight GUI or via command line pilight-send. Switches are operating correctly though.

I have a problem getting the situation right. I got you have dimmers configured with pilight (sending mode). An additional Homebridge (with this plugin) is only an additional actor using pilight eventually. But this one cannot intercept your direct calls to pilight itself. Except there is an event overflow (see first my lines), I had not such issues so far.

**Comment by genfersee** [comment]
Closing this old issue, replaced by issue #43
