### ISSUE TITLE
The dimmer does not light on via Homekit app

### ISSUE THREAD

**Issue by genfersee** [knalli/homebridge-pilight#43]
Dear all,

### Pre Steps
I am using Homebridge with Homebridge-pilight plugin and pilight behind.

### Expected Behavior
On setting ON a dimmer via Homekit app, physical dimmer should light on to the latest % of brightness of that dimmer.

### Current Behavior and steps to Reproduce (for bugs)
Issue is the following:
When setting ON a dimmer via Homekit app:
- The physical dimmer does not light on (which is incorrect)
- The GUI dimmer shows 100% instead of the latest % of brightness of the dimmer (which is incorrect)

Then, I set the dimmer OFF via Homekit app:
- The physical dimmer remains off
- The GUI dimmer switches to OFF (which is correct)

Then, I set the dimmer ON via Homekit app:
- The physical dimmer lights on to the latest % of brightness of the dimmer (which is correct !)
- The GUI dimmer shows 100% brightness (which is incorrect) instead of the latest % of brightness of the dimmer.

### Versions

- **Homebridge**: `0.4.45`
- **Node**:       `9.11.2`
- **OS**:         Raspberry PI3 

### Configuration

Config pilight:
`"Dimmer11": {
			"protocol": [ "kaku_dimmer" ],
			"id": [{
				"id": XXXXXXX,
				"unit": 1
			}],
			"state": "off",
			"dimlevel-minimum": 1,
			"dimlevel-maximum": 15,
			"dimlevel": 14
		}`

Config Homebridge:

`{
	"bridge": {
		"name": "Homebridge",
		"username": "XX:XX:XX:XX:XX:XX",
		"port": XXXX,
		"pin": "XXX-XX-XXX"
	},
	"description": "This is my Homebridge Config file",
	"accessories": [
		{
		"accessory": "pilight",
      		"name": "Plafond",
      		"device": "Dimmer11",
		"type": "Dimmer",
      		"sharedWS": false
		}
	],
	"platforms": [
	]
}`

### Homebridge Log / Command Output

```

```

**Comment by knalli** [comment]
> Before posting the logs, could you please tell if this is the expected behaviour?

Honestly, I don't know either. I have no devices with dimmer which are connected via Homebridge (only "directly" via Trådfri). Sometimes these are also a little bit glitchy speaking of your description. But at the most time, my preferred setting of xx% is working with on/off on two iOS devices in parallel without issues.

**Comment by genfersee** [comment]
Thanks for your feedback!
I have investigated a bit further and updated the issue description.
I can confirm that Pilight behaves correctly since status in Pilight is always the one expected at any moment.
The issue happens all the time, on 2 different setup I have, for all the dimmers I have...

**Comment by genfersee** [comment]
I found a workaround: define the dimmers as switch in Homebridge.

**Comment by genfersee** [comment]
I reopen this issue since I really want to be able to use the dimmer as a dimmer and not as a switch :)

I captured some logs for the following different bugs:

**_1st bug:_**
In the case I ask Siri to activate the light, the physical light is properly dimmed ON to 50% but the dim percentage displayed in Home app is incorrect: 0% instead of 50% (50% being the last intensity used):
`[2020-2-12 1:13:05 PM] [Table] [homebridge-pilight] Try to set powerstate to "on"`
`[2020-2-12 1:13:05 PM] [Table] [homebridge-pilight] Updated internal state to "on"`
It seems that when Siri lights on a light, it sends only a ON command, and not a DIM command.

**_2nd bug:_**
If I tap on light Homekit icon, it switches ON the physical light but dim it to 100% instead of 50%(50% being the last intensity used):
`[2020-2-12 1:32:08 PM] [Table] [homebridge-pilight] Try to set dim level to 15 for value 100`
`[2020-2-12 1:32:08 PM] [Table] [homebridge-pilight] Try to set powerstate to "on"`
`[2020-2-12 1:32:08 PM] [Table] [homebridge-pilight] Updated internal state to "on"`
`[2020-2-12 1:32:08 PM] [Table] [homebridge-pilight] Updated internal dim level to 15`

**_3rd bug:_**
If I tap on light Homekit icon, it switches ON the icon but not the Physical light. A steering weel keeps rolling in the icon:
`[2020-2-12 1:34:59 PM] [Table] [homebridge-pilight] Try to set dim level to 15 for value 100`
`[2020-2-12 1:34:59 PM] [Table] [homebridge-pilight] Try to set powerstate to "on"`

**_4th bug:_**
In the case of an activation of the light via a Homekit automation (dim the light at 50%), the physical light is not light on. Status of the light in Pilight also remains OFF. We can see that indeed, no internal messages are sent. Why?:
`[2020-2-12 1:14:44 PM] [Table] [homebridge-pilight] Try to set dim level to 7 for value 50`
`[2020-2-12 1:14:44 PM] [Table] [homebridge-pilight] Try to set powerstate to "on"`

Then, if I force the automation to be executed again, then it works properly and the light is switched ON and dimmed to 50%:
`[2020-2-12 1:15:39 PM] [Table] [homebridge-pilight] Try to set dim level to 7 for value 50`
`[2020-2-12 1:15:39 PM] [Table] [homebridge-pilight] Try to set powerstate to "on"`
`[2020-2-12 1:15:39 PM] [Table] [homebridge-pilight] Updated internal state to "on"`
`[2020-2-12 1:15:39 PM] [Table] [homebridge-pilight] Updated internal dim level to 7`

**Comment by genfersee** [comment]
I replaced my Intertechno dimmers with some other device.

**Comment by knalli** [comment]
And that one is working better?

**Comment by genfersee** [comment]
Well in fact, I changed to Shelly dimmer, so no more need for plight ;-)

**Comment by knalli** [comment]
Yeah, shelly seems to be fine.. ;)
