### ISSUE TITLE
Link to a walkthrough?

### ISSUE THREAD

**Issue by hepcat72** [knalli/homebridge-pilight#45]
Is there a blog post or or other documentation that walks you from point A (being able to turn on/off Etekcity outlets using pilight-send) to point B (being able to use homebridge-pilight) to control those outlets?

I assume there’s just some installations and configuration setup to do this. No coding necessary?

**Comment by knalli** [comment]
@hepcat72  What do you mean exactly?

* The documentation for pilight itself will be available at them, I don't cover this.
* After configuring this, you can apply a configuration in homebridge (for this plugin), see readme: https://github.com/knalli/homebridge-pilight#example-configjson

That's it.

**Comment by hepcat72** [comment]
Oh ok. Yeah. I went through the pilight config stuff awhile back (memory’s not that great). The issue is that there’s not a protocol for Etekcity outlets. I use the raw protocol for my pilight-send commands. I’d have to write a protocol in order to setup a config in pilight for my outlets. So never mind I guess. I already set up the outlets using homebridge-commander which was easier from my standpoint. I just wondered if I could do it with this plugin.

**Comment by knalli** [comment]
Well, if your devices are not working with pilight and you are looking for a solution for homebridge, you might skip pilight just and build a binding for homebridge directly.

**Comment by hepcat72** [comment]
I mean, I use pilight-send successfully with the raw protocol. And I’ve set things up via homebridge-commander to issue those calls. My next problem is I would like to control outlets via triggers from IFTTT. I haven’t figured out yet how to accomplish that. The homebridge-ifttt plugin is only for going from pi to IFTTT, not the other direction. I saw that homebridge-pilight used websockets and I was curious if it could be used to control the outlets using IFTTT.

So where can I learn what a binding is?

**Comment by knalli** [comment]
Well, the websocket is provided by pilight as it does not only transmit but also consume data.

I'm not familiar with the IFTTT apis; for this and also homebridge you should consult the specific docs. For homebridge you find samples for everything (the actual existing bindings).
